### ISSUE TITLE
大佬好厉害

### ISSUE THREAD

**Issue by FallingSakura** [LeafYeeXYZ/PsychPen#1]
RT，想听大佬的学习路径和所面临的困难、花费的时间。

**Comment by LeafYeeXYZ** [comment]
除了在学校课程中学了一点 `C` 和 `MATLAB` 之外, 自己学编程大概是始于一年前跟着教程搭建 `Hexo` 博客, 之后的学习路径大概是:

1. 看黑马程序员上的 javascript 教程 (中途讲到 dom 和 bom 的时候去速成了一下 html)
2. 之后看了他们的 html 和 css 教程
3. 再之后看了他们的“框架前置课” (讲了点计算机网络, ajax, node.js 这些), 看 MDN 自学了 fetch API (视频课程可能比较老)
4. 自己翻 MDN 和一些视频学习了一些比较新的 JS 语法 (包括 class、bigint 这些, 同样视频课程里没有)
5. 打眼看了看 vue 和 react 的文档, 自己喜欢后者的风格, 于是就翻文档自学 react
6. 后面就基本上是做项目的时候需要学习什么、自己对什么感兴趣, 就看官方文档学习~

在各位 AI 老师的帮忙下暂时没有遇到什么克服不了的困难, 也是赶上了好时代了

**Comment by FallingSakura** [comment]
> 除了在学校课程中学了一点 `C` 和 `MATLAB` 之外, 自己学编程大概是**始于一年前**跟着教程搭建 `Hexo` 博客, 之后的学习路径大概是:
> 
> 1. 看黑马程序员上的 javascript 教程 (中途讲到 dom 和 bom 的时候去速成了一下 html)
> 2. 之后看了他们的 html 和 css 教程
> 3. 再之后看了他们的“框架前置课” (讲了点计算机网络, ajax, node.js 这些), 看 MDN 自学了 fetch API (视频课程可能比较老)
> 4. 自己翻 MDN 和一些视频学习了一些比较新的 JS 语法 (包括 class、bigint 这些, 同样视频课程里没有)
> 5. 打眼看了看 vue 和 react 的文档, 自己喜欢后者的风格, 于是就翻文档自学 react
> 6. 后面就基本上是做项目的时候需要学习什么、自己对什么感兴趣, 就看官方文档学习~
> 
> 在各位 **AI 老师的帮忙**下暂时没有遇到什么克服不了的困难, 也是赶上了好时代了

哇，居然出奇地一致欸，看来我的学习速度还是没有落后多少的，受教了。
